package com.escola.matriculas.domain.enums;

public enum Curso {
    TECNICO_ADMINISTRACAO,
    TECNICO_EM_INFORMATICA,
    TECNICO_LOGISTICA,
    TECNICO_EM_EDIFICACOES,
    TECNICO_EM_ELETROTECNICA,
    TECNICO_EM_ELETROMECANICA,
    TECNICO_EM_QUIMICA,
    TECNICO_SEGURANCA_DO_TRABALHO
}
