package com.escola.matriculas.domain.enums;

public enum Curso {
    TECNICO_ADMINISTRACAO,
    TECNICO_INFORMATICA,
    TECNICO_LOGISTICA,
    TECNICO_EDIFICACOES,
    TECNICO_ELETROTECNICA,
    TECNICO_ELETROMECANICA,
    TECNICO_QUIMICA,
    TECNICO_SEGURANCA_DO_TRABALHO
}
